language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4_1.gemfile
  include:
    - rvm: 2.4.3
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_master.gemfile
install: bundle install
script: bundle exec rspec
