language: ruby
rvm:
  - 2.2.2
  - 2.1.2
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
script: bundle exec rspec
